version: '3.8'

services:
  wedding-app:
    build: .
    container_name: wedding-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend/config.json:/app/config.json
      - ./backend/credentials.json:/app/credentials.json
